// Omni Gateway management console: supported interface locales.

const SUPPORTED_LOCALES = {
    en: {
        label: 'English',
        messages: {
            language: 'Language', dashboard: 'Dashboard', pool: 'Pool', models: 'Models', providers: 'Providers', settings: 'Settings', logs: 'Logs', about: 'About',
            sign_out: 'Sign out', sign_in_title: 'Sign In to the Console', login_copy: 'Manage routing, credentials, fallback behavior, and protocol translation from one focused workspace.',
            console_password: 'Console password', enter_password: 'Enter password', continue: 'Continue', setup_title: 'Create Your Console Password', setup_copy: 'Secure this new Omni Gateway instance before opening the management console.',
            confirm_password: 'Confirm password', create_password: 'Create password', footer_tagline: 'Universal AI routing for coding tools.',
            dashboard_title: 'Omni Gateway Dashboard', dashboard_description: 'Monitor request flow, provider capacity, and integration details for coding-tool traffic.',
            pool_title: 'Provider Credential Pool', pool_description: 'Manage accounts and API keys from every connected provider. Monitor credential health, routing capacity, and pool backups from one place.',
            models_title: 'Routing Models', models_description: 'Manage virtual model routes and inspect provider models available to the shared credential pool.',
            providers_title: 'Add Provider Credentials', providers_description: 'Choose a provider, connect an account or API key, and add it to the shared routing pool.',
            settings_title: 'System Configuration', settings_description: 'Tune console access, storage, proxy, retry policy, response translation, and keep-alive behavior.',
            logs_title: 'Runtime Log Stream', logs_description: 'Watch routing decisions, upstream responses, credential rotation, and application errors.',
            about_description: 'A universal AI router for coding tools with smart auto-fallback, token-aware request cleanup, usage visibility, and seamless format translation.'
        }
    },
    'zh-CN': {
        label: '中文(简体)',
        messages: {
            language: '语言', dashboard: '仪表板', pool: '凭据池', models: '模型', providers: '提供商', settings: '设置', logs: '日志', about: '关于',
            sign_out: '退出登录', sign_in_title: '登录控制台', login_copy: '在一个专注的工作区中管理路由、凭据、故障转移策略和协议转换。',
            console_password: '控制台密码', enter_password: '输入密码', continue: '继续', setup_title: '创建控制台密码', setup_copy: '在打开管理控制台前，请先保护这个新的 Omni Gateway 实例。',
            confirm_password: '确认密码', create_password: '创建密码', footer_tagline: '面向编码工具的通用 AI 路由。',
            dashboard_title: 'Omni Gateway 仪表板', dashboard_description: '监控编码工具流量的请求流、提供商容量和集成详情。',
            pool_title: '提供商凭据池', pool_description: '集中管理所有已连接提供商的账户和 API 密钥，并监控凭据健康度、路由容量和池备份。',
            models_title: '路由模型', models_description: '管理虚拟模型路由，并查看共享凭据池中可用的提供商模型。',
            providers_title: '添加提供商凭据', providers_description: '选择提供商，连接账户或 API 密钥，然后将其加入共享路由池。',
            settings_title: '系统配置', settings_description: '调整控制台访问、存储、代理、重试策略、响应转换和保活行为。',
            logs_title: '运行时日志流', logs_description: '查看路由决策、上游响应、凭据轮换和应用错误。',
            about_description: '面向编码工具的通用 AI 路由器，提供智能自动故障转移、令牌感知的请求清理、使用情况可见性和无缝格式转换。'
        }
    },
    'zh-TW': {
        label: '中文(繁體)',
        messages: {
            language: '語言', dashboard: '儀表板', pool: '憑證集區', models: '模型', providers: '供應商', settings: '設定', logs: '日誌', about: '關於',
            sign_out: '登出', sign_in_title: '登入主控台', login_copy: '在單一專注的工作區中管理路由、憑證、容錯行為與通訊協定轉換。',
            console_password: '主控台密碼', enter_password: '輸入密碼', continue: '繼續', setup_title: '建立主控台密碼', setup_copy: '開啟管理主控台前，請先保護這個新的 Omni Gateway 執行個體。',
            confirm_password: '確認密碼', create_password: '建立密碼', footer_tagline: '適用於程式開發工具的通用 AI 路由。',
            dashboard_title: 'Omni Gateway 儀表板', dashboard_description: '監控程式開發工具流量的請求流程、供應商容量與整合詳細資料。',
            pool_title: '供應商憑證集區', pool_description: '集中管理每個已連線供應商的帳戶與 API 金鑰，並監控憑證健康度、路由容量與集區備份。',
            models_title: '路由模型', models_description: '管理虛擬模型路由，並檢視共用憑證集區可用的供應商模型。',
            providers_title: '新增供應商憑證', providers_description: '選擇供應商、連線帳戶或 API 金鑰，然後加入共用路由集區。',
            settings_title: '系統設定', settings_description: '調整主控台存取、儲存空間、Proxy、重試策略、回應轉換與保活行為。',
            logs_title: '執行階段日誌串流', logs_description: '檢視路由決策、上游回應、憑證輪替與應用程式錯誤。',
            about_description: '適用於程式開發工具的通用 AI 路由器，提供智慧自動容錯、權杖感知請求清理、用量可見性與無縫格式轉換。'
        }
    },
    de: {
        label: 'Deutsch',
        messages: {
            language: 'Sprache', dashboard: 'Dashboard', pool: 'Pool', models: 'Modelle', providers: 'Anbieter', settings: 'Einstellungen', logs: 'Protokolle', about: 'Info',
            sign_out: 'Abmelden', sign_in_title: 'Bei der Konsole anmelden', login_copy: 'Verwalten Sie Routing, Zugangsdaten, Failover-Verhalten und Protokollübersetzung in einem fokussierten Arbeitsbereich.',
            console_password: 'Konsolenpasswort', enter_password: 'Passwort eingeben', continue: 'Weiter', setup_title: 'Konsolenpasswort erstellen', setup_copy: 'Sichern Sie diese neue Omni-Gateway-Instanz, bevor Sie die Verwaltungskonsole öffnen.',
            confirm_password: 'Passwort bestätigen', create_password: 'Passwort erstellen', footer_tagline: 'Universelles KI-Routing für Coding-Tools.',
            dashboard_title: 'Omni Gateway Dashboard', dashboard_description: 'Überwachen Sie Anfragefluss, Anbieterkapazität und Integrationsdetails für den Traffic Ihrer Coding-Tools.',
            pool_title: 'Anbieter-Zugangsdatenpool', pool_description: 'Verwalten Sie Konten und API-Schlüssel aller verbundenen Anbieter. Behalten Sie Zustand, Routing-Kapazität und Pool-Backups an einem Ort im Blick.',
            models_title: 'Routing-Modelle', models_description: 'Verwalten Sie virtuelle Modellrouten und prüfen Sie die im gemeinsamen Zugangsdatenpool verfügbaren Anbietermodelle.',
            providers_title: 'Anbieter-Zugangsdaten hinzufügen', providers_description: 'Wählen Sie einen Anbieter, verbinden Sie ein Konto oder einen API-Schlüssel und fügen Sie ihn dem gemeinsamen Routing-Pool hinzu.',
            settings_title: 'Systemkonfiguration', settings_description: 'Konfigurieren Sie Konsolenzugriff, Speicher, Proxy, Wiederholungsstrategie, Antwortübersetzung und Keep-Alive-Verhalten.',
            logs_title: 'Laufzeit-Protokollstream', logs_description: 'Beobachten Sie Routing-Entscheidungen, Upstream-Antworten, Zugangsdatenrotation und Anwendungsfehler.',
            about_description: 'Ein universeller KI-Router für Coding-Tools mit intelligentem Auto-Failover, tokenbewusster Anfragebereinigung, Nutzungsübersicht und nahtloser Formatübersetzung.'
        }
    },
    es: {
        label: 'Español',
        messages: {
            language: 'Idioma', dashboard: 'Panel', pool: 'Grupo', models: 'Modelos', providers: 'Proveedores', settings: 'Configuración', logs: 'Registros', about: 'Acerca de',
            sign_out: 'Cerrar sesión', sign_in_title: 'Iniciar sesión en la consola', login_copy: 'Administra el enrutamiento, las credenciales, el comportamiento de conmutación por error y la traducción de protocolos desde un espacio de trabajo enfocado.',
            console_password: 'Contraseña de la consola', enter_password: 'Introduce la contraseña', continue: 'Continuar', setup_title: 'Crea la contraseña de la consola', setup_copy: 'Protege esta nueva instancia de Omni Gateway antes de abrir la consola de administración.',
            confirm_password: 'Confirmar contraseña', create_password: 'Crear contraseña', footer_tagline: 'Enrutamiento universal de IA para herramientas de programación.',
            dashboard_title: 'Panel de Omni Gateway', dashboard_description: 'Supervisa el flujo de solicitudes, la capacidad de los proveedores y los detalles de integración del tráfico de herramientas de programación.',
            pool_title: 'Grupo de credenciales de proveedores', pool_description: 'Administra cuentas y claves API de todos los proveedores conectados. Supervisa el estado de las credenciales, la capacidad de enrutamiento y las copias de seguridad desde un solo lugar.',
            models_title: 'Modelos de enrutamiento', models_description: 'Administra rutas de modelos virtuales e inspecciona los modelos de proveedores disponibles en el grupo compartido de credenciales.',
            providers_title: 'Añadir credenciales de proveedor', providers_description: 'Elige un proveedor, conecta una cuenta o una clave API y añádela al grupo de enrutamiento compartido.',
            settings_title: 'Configuración del sistema', settings_description: 'Ajusta el acceso a la consola, el almacenamiento, el proxy, la política de reintentos, la traducción de respuestas y el comportamiento de keep-alive.',
            logs_title: 'Flujo de registros de ejecución', logs_description: 'Consulta decisiones de enrutamiento, respuestas ascendentes, rotación de credenciales y errores de la aplicación.',
            about_description: 'Un router de IA universal para herramientas de programación con conmutación automática inteligente, limpieza de solicitudes basada en tokens, visibilidad de uso y traducción de formatos fluida.'
        }
    },
    fr: {
        label: 'Français',
        messages: {
            language: 'Langue', dashboard: 'Tableau de bord', pool: 'Pool', models: 'Modèles', providers: 'Fournisseurs', settings: 'Paramètres', logs: 'Journaux', about: 'À propos',
            sign_out: 'Se déconnecter', sign_in_title: 'Se connecter à la console', login_copy: 'Gérez le routage, les identifiants, le basculement et la traduction de protocoles depuis un espace de travail unique.',
            console_password: 'Mot de passe de la console', enter_password: 'Saisir le mot de passe', continue: 'Continuer', setup_title: 'Créer le mot de passe de la console', setup_copy: 'Sécurisez cette nouvelle instance Omni Gateway avant d’ouvrir la console d’administration.',
            confirm_password: 'Confirmer le mot de passe', create_password: 'Créer le mot de passe', footer_tagline: 'Routage IA universel pour les outils de développement.',
            dashboard_title: 'Tableau de bord Omni Gateway', dashboard_description: 'Suivez le flux des requêtes, la capacité des fournisseurs et les détails d’intégration du trafic des outils de développement.',
            pool_title: 'Pool d’identifiants fournisseurs', pool_description: 'Gérez les comptes et clés API de chaque fournisseur connecté. Suivez l’état des identifiants, la capacité de routage et les sauvegardes du pool au même endroit.',
            models_title: 'Modèles de routage', models_description: 'Gérez les routes de modèles virtuels et examinez les modèles fournisseurs disponibles dans le pool d’identifiants partagé.',
            providers_title: 'Ajouter des identifiants fournisseur', providers_description: 'Choisissez un fournisseur, connectez un compte ou une clé API, puis ajoutez-le au pool de routage partagé.',
            settings_title: 'Configuration système', settings_description: 'Réglez l’accès à la console, le stockage, le proxy, la politique de relance, la traduction des réponses et le keep-alive.',
            logs_title: 'Flux de journaux d’exécution', logs_description: 'Consultez les décisions de routage, les réponses amont, la rotation des identifiants et les erreurs applicatives.',
            about_description: 'Un routeur IA universel pour les outils de développement, avec basculement automatique intelligent, nettoyage des requêtes tenant compte des tokens, visibilité de l’utilisation et traduction de formats fluide.'
        }
    },
    id: {
        label: 'Indonesia',
        messages: {
            language: 'Bahasa', dashboard: 'Dasbor', pool: 'Pool', models: 'Model', providers: 'Penyedia', settings: 'Pengaturan', logs: 'Log', about: 'Tentang',
            sign_out: 'Keluar', sign_in_title: 'Masuk ke Konsol', login_copy: 'Kelola perutean, kredensial, perilaku failover, dan penerjemahan protokol dari satu ruang kerja yang terfokus.',
            console_password: 'Kata sandi konsol', enter_password: 'Masukkan kata sandi', continue: 'Lanjutkan', setup_title: 'Buat Kata Sandi Konsol', setup_copy: 'Amankan instans Omni Gateway baru ini sebelum membuka konsol pengelolaan.',
            confirm_password: 'Konfirmasi kata sandi', create_password: 'Buat kata sandi', footer_tagline: 'Perutean AI universal untuk alat pemrograman.',
            dashboard_title: 'Dasbor Omni Gateway', dashboard_description: 'Pantau aliran permintaan, kapasitas penyedia, dan detail integrasi untuk trafik alat pemrograman.',
            pool_title: 'Pool Kredensial Penyedia', pool_description: 'Kelola akun dan kunci API dari setiap penyedia yang terhubung. Pantau kesehatan kredensial, kapasitas perutean, dan cadangan pool dari satu tempat.',
            models_title: 'Model Perutean', models_description: 'Kelola rute model virtual dan periksa model penyedia yang tersedia bagi pool kredensial bersama.',
            providers_title: 'Tambahkan Kredensial Penyedia', providers_description: 'Pilih penyedia, hubungkan akun atau kunci API, lalu tambahkan ke pool perutean bersama.',
            settings_title: 'Konfigurasi Sistem', settings_description: 'Atur akses konsol, penyimpanan, proxy, kebijakan percobaan ulang, penerjemahan respons, dan perilaku keep-alive.',
            logs_title: 'Aliran Log Runtime', logs_description: 'Pantau keputusan perutean, respons upstream, rotasi kredensial, dan kesalahan aplikasi.',
            about_description: 'Router AI universal untuk alat pemrograman dengan failover otomatis yang cerdas, pembersihan permintaan sadar token, visibilitas penggunaan, dan penerjemahan format yang mulus.'
        }
    },
    it: {
        label: 'Italiano',
        messages: {
            language: 'Lingua', dashboard: 'Dashboard', pool: 'Pool', models: 'Modelli', providers: 'Provider', settings: 'Impostazioni', logs: 'Log', about: 'Informazioni',
            sign_out: 'Esci', sign_in_title: 'Accedi alla console', login_copy: 'Gestisci routing, credenziali, comportamento di failover e traduzione dei protocolli da un unico spazio di lavoro.',
            console_password: 'Password della console', enter_password: 'Inserisci la password', continue: 'Continua', setup_title: 'Crea la password della console', setup_copy: 'Proteggi questa nuova istanza Omni Gateway prima di aprire la console di gestione.',
            confirm_password: 'Conferma password', create_password: 'Crea password', footer_tagline: 'Routing IA universale per strumenti di sviluppo.',
            dashboard_title: 'Dashboard Omni Gateway', dashboard_description: 'Monitora il flusso delle richieste, la capacità dei provider e i dettagli di integrazione per il traffico degli strumenti di sviluppo.',
            pool_title: 'Pool di credenziali provider', pool_description: 'Gestisci account e chiavi API di ogni provider connesso. Monitora stato delle credenziali, capacità di routing e backup del pool da un unico punto.',
            models_title: 'Modelli di routing', models_description: 'Gestisci percorsi di modelli virtuali e controlla i modelli provider disponibili nel pool condiviso di credenziali.',
            providers_title: 'Aggiungi credenziali provider', providers_description: 'Scegli un provider, collega un account o una chiave API e aggiungilo al pool di routing condiviso.',
            settings_title: 'Configurazione di sistema', settings_description: 'Regola accesso alla console, archiviazione, proxy, criteri di tentativo, traduzione delle risposte e comportamento keep-alive.',
            logs_title: 'Flusso log di runtime', logs_description: 'Osserva decisioni di routing, risposte upstream, rotazione delle credenziali ed errori dell’applicazione.',
            about_description: 'Un router IA universale per strumenti di sviluppo con failover automatico intelligente, pulizia delle richieste basata sui token, visibilità dell’utilizzo e traduzione dei formati senza interruzioni.'
        }
    },
    ja: {
        label: '日本語',
        messages: {
            language: '言語', dashboard: 'ダッシュボード', pool: 'プール', models: 'モデル', providers: 'プロバイダー', settings: '設定', logs: 'ログ', about: '概要',
            sign_out: 'サインアウト', sign_in_title: 'コンソールにサインイン', login_copy: 'ルーティング、認証情報、フェイルオーバー動作、プロトコル変換を一つのワークスペースで管理します。',
            console_password: 'コンソールのパスワード', enter_password: 'パスワードを入力', continue: '続行', setup_title: 'コンソールのパスワードを作成', setup_copy: '管理コンソールを開く前に、この新しい Omni Gateway インスタンスを保護してください。',
            confirm_password: 'パスワードを確認', create_password: 'パスワードを作成', footer_tagline: 'コーディングツールのためのユニバーサル AI ルーティング。',
            dashboard_title: 'Omni Gateway ダッシュボード', dashboard_description: 'コーディングツールのトラフィックについて、リクエストフロー、プロバイダー容量、統合の詳細を監視します。',
            pool_title: 'プロバイダー認証情報プール', pool_description: '接続済みプロバイダーのアカウントと API キーを管理し、認証情報の状態、ルーティング容量、プールのバックアップを一か所で確認します。',
            models_title: 'ルーティングモデル', models_description: '仮想モデルルートを管理し、共有認証情報プールで利用できるプロバイダーモデルを確認します。',
            providers_title: 'プロバイダー認証情報を追加', providers_description: 'プロバイダーを選択し、アカウントまたは API キーを接続して、共有ルーティングプールに追加します。',
            settings_title: 'システム設定', settings_description: 'コンソールアクセス、ストレージ、プロキシ、再試行ポリシー、応答変換、キープアライブ動作を調整します。',
            logs_title: 'ランタイムログストリーム', logs_description: 'ルーティングの判断、上流応答、認証情報のローテーション、アプリケーションエラーを確認します。',
            about_description: 'スマートな自動フェイルオーバー、トークンを考慮したリクエスト整理、利用状況の可視化、シームレスな形式変換を備えたコーディングツール向けユニバーサル AI ルーター。'
        }
    },
    ko: {
        label: '한국어',
        messages: {
            language: '언어', dashboard: '대시보드', pool: '풀', models: '모델', providers: '공급자', settings: '설정', logs: '로그', about: '정보',
            sign_out: '로그아웃', sign_in_title: '콘솔에 로그인', login_copy: '하나의 집중된 작업 공간에서 라우팅, 자격 증명, 장애 조치 동작, 프로토콜 변환을 관리하세요.',
            console_password: '콘솔 비밀번호', enter_password: '비밀번호 입력', continue: '계속', setup_title: '콘솔 비밀번호 만들기', setup_copy: '관리 콘솔을 열기 전에 새 Omni Gateway 인스턴스를 보호하세요.',
            confirm_password: '비밀번호 확인', create_password: '비밀번호 만들기', footer_tagline: '코딩 도구를 위한 범용 AI 라우팅.',
            dashboard_title: 'Omni Gateway 대시보드', dashboard_description: '코딩 도구 트래픽의 요청 흐름, 공급자 용량, 통합 세부 정보를 모니터링합니다.',
            pool_title: '공급자 자격 증명 풀', pool_description: '연결된 모든 공급자의 계정과 API 키를 관리하세요. 자격 증명 상태, 라우팅 용량, 풀 백업을 한곳에서 확인할 수 있습니다.',
            models_title: '라우팅 모델', models_description: '가상 모델 경로를 관리하고 공유 자격 증명 풀에서 사용할 수 있는 공급자 모델을 확인하세요.',
            providers_title: '공급자 자격 증명 추가', providers_description: '공급자를 선택하고 계정 또는 API 키를 연결한 후 공유 라우팅 풀에 추가하세요.',
            settings_title: '시스템 구성', settings_description: '콘솔 접근, 저장소, 프록시, 재시도 정책, 응답 변환, keep-alive 동작을 조정합니다.',
            logs_title: '런타임 로그 스트림', logs_description: '라우팅 결정, 업스트림 응답, 자격 증명 순환, 애플리케이션 오류를 확인합니다.',
            about_description: '스마트 자동 장애 조치, 토큰 인식 요청 정리, 사용량 가시성, 원활한 형식 변환을 제공하는 코딩 도구용 범용 AI 라우터입니다.'
        }
    },
    pt: {
        label: 'Português',
        messages: {
            language: 'Idioma', dashboard: 'Painel', pool: 'Pool', models: 'Modelos', providers: 'Provedores', settings: 'Configurações', logs: 'Logs', about: 'Sobre',
            sign_out: 'Sair', sign_in_title: 'Entrar no Console', login_copy: 'Gerencie roteamento, credenciais, comportamento de failover e tradução de protocolos em um espaço de trabalho focado.',
            console_password: 'Senha do console', enter_password: 'Digite a senha', continue: 'Continuar', setup_title: 'Crie a Senha do Console', setup_copy: 'Proteja esta nova instância do Omni Gateway antes de abrir o console de gerenciamento.',
            confirm_password: 'Confirmar senha', create_password: 'Criar senha', footer_tagline: 'Roteamento universal de IA para ferramentas de programação.',
            dashboard_title: 'Painel do Omni Gateway', dashboard_description: 'Monitore o fluxo de solicitações, a capacidade dos provedores e os detalhes de integração do tráfego de ferramentas de programação.',
            pool_title: 'Pool de Credenciais de Provedores', pool_description: 'Gerencie contas e chaves de API de todos os provedores conectados. Acompanhe a integridade das credenciais, a capacidade de roteamento e os backups do pool em um só lugar.',
            models_title: 'Modelos de Roteamento', models_description: 'Gerencie rotas de modelos virtuais e inspecione os modelos de provedores disponíveis no pool compartilhado de credenciais.',
            providers_title: 'Adicionar Credenciais de Provedor', providers_description: 'Escolha um provedor, conecte uma conta ou chave de API e adicione-a ao pool de roteamento compartilhado.',
            settings_title: 'Configuração do Sistema', settings_description: 'Ajuste o acesso ao console, armazenamento, proxy, política de tentativas, tradução de respostas e comportamento de keep-alive.',
            logs_title: 'Fluxo de Logs de Execução', logs_description: 'Acompanhe decisões de roteamento, respostas upstream, rotação de credenciais e erros da aplicação.',
            about_description: 'Um roteador de IA universal para ferramentas de programação com failover automático inteligente, limpeza de solicitações orientada por tokens, visibilidade de uso e tradução de formatos integrada.'
        }
    },
    ru: {
        label: 'Русский',
        messages: {
            language: 'Язык', dashboard: 'Панель', pool: 'Пул', models: 'Модели', providers: 'Провайдеры', settings: 'Настройки', logs: 'Журналы', about: 'О проекте',
            sign_out: 'Выйти', sign_in_title: 'Войти в консоль', login_copy: 'Управляйте маршрутизацией, учётными данными, отказоустойчивостью и преобразованием протоколов в едином рабочем пространстве.',
            console_password: 'Пароль консоли', enter_password: 'Введите пароль', continue: 'Продолжить', setup_title: 'Создайте пароль консоли', setup_copy: 'Защитите новый экземпляр Omni Gateway перед открытием консоли управления.',
            confirm_password: 'Подтвердите пароль', create_password: 'Создать пароль', footer_tagline: 'Универсальная маршрутизация ИИ для инструментов разработки.',
            dashboard_title: 'Панель Omni Gateway', dashboard_description: 'Отслеживайте поток запросов, возможности провайдеров и детали интеграции трафика инструментов разработки.',
            pool_title: 'Пул учётных данных провайдеров', pool_description: 'Управляйте аккаунтами и API-ключами всех подключённых провайдеров. Контролируйте состояние учётных данных, ресурсы маршрутизации и резервные копии пула в одном месте.',
            models_title: 'Модели маршрутизации', models_description: 'Управляйте маршрутами виртуальных моделей и просматривайте модели провайдеров, доступные в общем пуле учётных данных.',
            providers_title: 'Добавить учётные данные провайдера', providers_description: 'Выберите провайдера, подключите аккаунт или API-ключ и добавьте его в общий пул маршрутизации.',
            settings_title: 'Конфигурация системы', settings_description: 'Настройте доступ к консоли, хранилище, прокси, политику повторов, преобразование ответов и keep-alive.',
            logs_title: 'Поток журналов выполнения', logs_description: 'Просматривайте решения маршрутизации, ответы upstream, ротацию учётных данных и ошибки приложения.',
            about_description: 'Универсальный ИИ-маршрутизатор для инструментов разработки с интеллектуальным автоматическим failover, очисткой запросов с учётом токенов, прозрачностью использования и бесшовным преобразованием форматов.'
        }
    },
    th: {
        label: 'ภาษาไทย',
        messages: {
            language: 'ภาษา', dashboard: 'แดชบอร์ด', pool: 'พูล', models: 'โมเดล', providers: 'ผู้ให้บริการ', settings: 'การตั้งค่า', logs: 'บันทึก', about: 'เกี่ยวกับ',
            sign_out: 'ออกจากระบบ', sign_in_title: 'ลงชื่อเข้าใช้คอนโซล', login_copy: 'จัดการการกำหนดเส้นทาง ข้อมูลรับรอง การทำงานเมื่อเกิดข้อผิดพลาด และการแปลงโปรโตคอลจากพื้นที่ทำงานเดียว',
            console_password: 'รหัสผ่านคอนโซล', enter_password: 'ป้อนรหัสผ่าน', continue: 'ดำเนินการต่อ', setup_title: 'สร้างรหัสผ่านคอนโซล', setup_copy: 'ปกป้องอินสแตนซ์ Omni Gateway ใหม่นี้ก่อนเปิดคอนโซลการจัดการ',
            confirm_password: 'ยืนยันรหัสผ่าน', create_password: 'สร้างรหัสผ่าน', footer_tagline: 'การกำหนดเส้นทาง AI สากลสำหรับเครื่องมือเขียนโค้ด',
            dashboard_title: 'แดชบอร์ด Omni Gateway', dashboard_description: 'ติดตามการไหลของคำขอ ความจุของผู้ให้บริการ และรายละเอียดการผสานรวมสำหรับทราฟฟิกของเครื่องมือเขียนโค้ด',
            pool_title: 'พูลข้อมูลรับรองผู้ให้บริการ', pool_description: 'จัดการบัญชีและ API key จากผู้ให้บริการที่เชื่อมต่อทั้งหมด ตรวจสอบสถานะข้อมูลรับรอง ความจุการกำหนดเส้นทาง และข้อมูลสำรองของพูลได้ในที่เดียว',
            models_title: 'โมเดลการกำหนดเส้นทาง', models_description: 'จัดการเส้นทางโมเดลเสมือนและตรวจสอบโมเดลของผู้ให้บริการที่มีในพูลข้อมูลรับรองร่วม',
            providers_title: 'เพิ่มข้อมูลรับรองผู้ให้บริการ', providers_description: 'เลือกผู้ให้บริการ เชื่อมต่อบัญชีหรือ API key แล้วเพิ่มลงในพูลการกำหนดเส้นทางร่วม',
            settings_title: 'การกำหนดค่าระบบ', settings_description: 'ปรับการเข้าถึงคอนโซล พื้นที่จัดเก็บ พร็อกซี นโยบายการลองใหม่ การแปลงการตอบกลับ และ keep-alive',
            logs_title: 'สตรีมบันทึกขณะทำงาน', logs_description: 'ดูการตัดสินใจกำหนดเส้นทาง การตอบกลับจากต้นทาง การหมุนเวียนข้อมูลรับรอง และข้อผิดพลาดของแอปพลิเคชัน',
            about_description: 'เราเตอร์ AI สากลสำหรับเครื่องมือเขียนโค้ด พร้อมการสลับเส้นทางอัตโนมัติอัจฉริยะ การล้างคำขอโดยคำนึงถึงโทเค็น การมองเห็นการใช้งาน และการแปลงรูปแบบอย่างราบรื่น'
        }
    },
    tr: {
        label: 'Türkçe',
        messages: {
            language: 'Dil', dashboard: 'Pano', pool: 'Havuz', models: 'Modeller', providers: 'Sağlayıcılar', settings: 'Ayarlar', logs: 'Günlükler', about: 'Hakkında',
            sign_out: 'Oturumu kapat', sign_in_title: 'Konsolda oturum aç', login_copy: 'Yönlendirmeyi, kimlik bilgilerini, yük devretme davranışını ve protokol çevirisini tek bir odaklı çalışma alanından yönetin.',
            console_password: 'Konsol parolası', enter_password: 'Parolayı girin', continue: 'Devam et', setup_title: 'Konsol Parolasını Oluştur', setup_copy: 'Yönetim konsolunu açmadan önce bu yeni Omni Gateway örneğini güvence altına alın.',
            confirm_password: 'Parolayı onayla', create_password: 'Parola oluştur', footer_tagline: 'Kodlama araçları için evrensel yapay zekâ yönlendirmesi.',
            dashboard_title: 'Omni Gateway Panosu', dashboard_description: 'Kodlama aracı trafiğinin istek akışını, sağlayıcı kapasitesini ve entegrasyon ayrıntılarını izleyin.',
            pool_title: 'Sağlayıcı Kimlik Bilgileri Havuzu', pool_description: 'Bağlı tüm sağlayıcıların hesaplarını ve API anahtarlarını yönetin. Kimlik bilgisi durumunu, yönlendirme kapasitesini ve havuz yedeklerini tek yerden izleyin.',
            models_title: 'Yönlendirme Modelleri', models_description: 'Sanal model rotalarını yönetin ve ortak kimlik bilgileri havuzunda bulunan sağlayıcı modellerini inceleyin.',
            providers_title: 'Sağlayıcı Kimlik Bilgileri Ekle', providers_description: 'Bir sağlayıcı seçin, hesap veya API anahtarı bağlayın ve ortak yönlendirme havuzuna ekleyin.',
            settings_title: 'Sistem Yapılandırması', settings_description: 'Konsol erişimini, depolamayı, proxy’yi, yeniden deneme ilkesini, yanıt çevirisini ve keep-alive davranışını ayarlayın.',
            logs_title: 'Çalışma Zamanı Günlük Akışı', logs_description: 'Yönlendirme kararlarını, upstream yanıtlarını, kimlik bilgisi dönüşümünü ve uygulama hatalarını izleyin.',
            about_description: 'Akıllı otomatik yük devretme, belirteç farkındalıklı istek temizleme, kullanım görünürlüğü ve sorunsuz biçim çevirisi sunan kodlama araçları için evrensel bir yapay zekâ yönlendiricisi.'
        }
    },
    vi: {
        label: 'Tiếng Việt',
        messages: {
            language: 'Ngôn ngữ', dashboard: 'Tổng quan', pool: 'Kho thông tin xác thực', models: 'Mô hình', providers: 'Nhà cung cấp', settings: 'Cài đặt', logs: 'Nhật ký', about: 'Giới thiệu',
            sign_out: 'Đăng xuất', sign_in_title: 'Đăng nhập vào bảng điều khiển', login_copy: 'Quản lý định tuyến, thông tin xác thực, cơ chế dự phòng và chuyển đổi giao thức trong một không gian làm việc tập trung.',
            console_password: 'Mật khẩu bảng điều khiển', enter_password: 'Nhập mật khẩu', continue: 'Tiếp tục', setup_title: 'Tạo mật khẩu bảng điều khiển', setup_copy: 'Bảo vệ phiên bản Omni Gateway mới này trước khi mở bảng điều khiển quản trị.',
            confirm_password: 'Xác nhận mật khẩu', create_password: 'Tạo mật khẩu', footer_tagline: 'Định tuyến AI phổ quát cho công cụ lập trình.',
            dashboard_title: 'Bảng điều khiển Omni Gateway', dashboard_description: 'Theo dõi luồng yêu cầu, năng lực nhà cung cấp và chi tiết tích hợp cho lưu lượng công cụ lập trình.',
            pool_title: 'Kho thông tin xác thực nhà cung cấp', pool_description: 'Quản lý tài khoản và khóa API từ mọi nhà cung cấp đã kết nối. Theo dõi trạng thái thông tin xác thực, năng lực định tuyến và bản sao lưu tại một nơi.',
            models_title: 'Mô hình định tuyến', models_description: 'Quản lý các tuyến mô hình ảo và kiểm tra mô hình của nhà cung cấp có trong kho thông tin xác thực dùng chung.',
            providers_title: 'Thêm thông tin xác thực nhà cung cấp', providers_description: 'Chọn nhà cung cấp, kết nối tài khoản hoặc khóa API, rồi thêm vào kho định tuyến dùng chung.',
            settings_title: 'Cấu hình hệ thống', settings_description: 'Điều chỉnh quyền truy cập bảng điều khiển, lưu trữ, proxy, chính sách thử lại, chuyển đổi phản hồi và cơ chế keep-alive.',
            logs_title: 'Luồng nhật ký thời gian chạy', logs_description: 'Theo dõi quyết định định tuyến, phản hồi upstream, quá trình luân phiên thông tin xác thực và lỗi ứng dụng.',
            about_description: 'Bộ định tuyến AI phổ quát cho công cụ lập trình với cơ chế dự phòng thông minh, làm sạch yêu cầu theo token, hiển thị mức sử dụng và chuyển đổi định dạng liền mạch.'
        }
    }
};

const COMMON_UI_TRANSLATIONS = {
    en: { save: 'Save', refresh: 'Refresh', import_zip: 'Import ZIP', download_zip: 'Download ZIP', download: 'Download', clear: 'Clear', reset_defaults: 'Reset defaults', check_for_updates: 'Check for updates', time_range: 'Time range', one_day: '1 day', seven_days: '7 days', thirty_days: '30 days', all: 'All', api_key: 'API key', openai_base_url: 'OpenAI base URL', anthropic_base_url: 'Anthropic base URL', google_genai_base_url: 'Google GenAI base URL' },
    'zh-CN': { save: '保存', refresh: '刷新', import_zip: '导入 ZIP', download_zip: '下载 ZIP', download: '下载', clear: '清除', reset_defaults: '恢复默认值', check_for_updates: '检查更新', time_range: '时间范围', one_day: '1 天', seven_days: '7 天', thirty_days: '30 天', all: '全部', api_key: 'API 密钥', openai_base_url: 'OpenAI 基础 URL', anthropic_base_url: 'Anthropic 基础 URL', google_genai_base_url: 'Google GenAI 基础 URL' },
    'zh-TW': { save: '儲存', refresh: '重新整理', import_zip: '匯入 ZIP', download_zip: '下載 ZIP', download: '下載', clear: '清除', reset_defaults: '還原預設值', check_for_updates: '檢查更新', time_range: '時間範圍', one_day: '1 天', seven_days: '7 天', thirty_days: '30 天', all: '全部', api_key: 'API 金鑰', openai_base_url: 'OpenAI 基礎 URL', anthropic_base_url: 'Anthropic 基礎 URL', google_genai_base_url: 'Google GenAI 基礎 URL' },
    de: { save: 'Speichern', refresh: 'Aktualisieren', import_zip: 'ZIP importieren', download_zip: 'ZIP herunterladen', download: 'Herunterladen', clear: 'Leeren', reset_defaults: 'Standardwerte wiederherstellen', check_for_updates: 'Nach Updates suchen', time_range: 'Zeitraum', one_day: '1 Tag', seven_days: '7 Tage', thirty_days: '30 Tage', all: 'Alle', api_key: 'API-Schlüssel', openai_base_url: 'OpenAI-Basis-URL', anthropic_base_url: 'Anthropic-Basis-URL', google_genai_base_url: 'Google-GenAI-Basis-URL' },
    es: { save: 'Guardar', refresh: 'Actualizar', import_zip: 'Importar ZIP', download_zip: 'Descargar ZIP', download: 'Descargar', clear: 'Limpiar', reset_defaults: 'Restablecer valores predeterminados', check_for_updates: 'Buscar actualizaciones', time_range: 'Periodo', one_day: '1 día', seven_days: '7 días', thirty_days: '30 días', all: 'Todo', api_key: 'Clave API', openai_base_url: 'URL base de OpenAI', anthropic_base_url: 'URL base de Anthropic', google_genai_base_url: 'URL base de Google GenAI' },
    fr: { save: 'Enregistrer', refresh: 'Actualiser', import_zip: 'Importer un ZIP', download_zip: 'Télécharger le ZIP', download: 'Télécharger', clear: 'Effacer', reset_defaults: 'Rétablir les valeurs par défaut', check_for_updates: 'Rechercher des mises à jour', time_range: 'Période', one_day: '1 jour', seven_days: '7 jours', thirty_days: '30 jours', all: 'Tout', api_key: 'Clé API', openai_base_url: 'URL de base OpenAI', anthropic_base_url: 'URL de base Anthropic', google_genai_base_url: 'URL de base Google GenAI' },
    id: { save: 'Simpan', refresh: 'Muat ulang', import_zip: 'Impor ZIP', download_zip: 'Unduh ZIP', download: 'Unduh', clear: 'Bersihkan', reset_defaults: 'Pulihkan default', check_for_updates: 'Periksa pembaruan', time_range: 'Rentang waktu', one_day: '1 hari', seven_days: '7 hari', thirty_days: '30 hari', all: 'Semua', api_key: 'Kunci API', openai_base_url: 'URL dasar OpenAI', anthropic_base_url: 'URL dasar Anthropic', google_genai_base_url: 'URL dasar Google GenAI' },
    it: { save: 'Salva', refresh: 'Aggiorna', import_zip: 'Importa ZIP', download_zip: 'Scarica ZIP', download: 'Scarica', clear: 'Cancella', reset_defaults: 'Ripristina predefiniti', check_for_updates: 'Verifica aggiornamenti', time_range: 'Intervallo di tempo', one_day: '1 giorno', seven_days: '7 giorni', thirty_days: '30 giorni', all: 'Tutti', api_key: 'Chiave API', openai_base_url: 'URL di base OpenAI', anthropic_base_url: 'URL di base Anthropic', google_genai_base_url: 'URL di base Google GenAI' },
    ja: { save: '保存', refresh: '更新', import_zip: 'ZIP をインポート', download_zip: 'ZIP をダウンロード', download: 'ダウンロード', clear: '消去', reset_defaults: '既定値に戻す', check_for_updates: '更新を確認', time_range: '期間', one_day: '1 日', seven_days: '7 日', thirty_days: '30 日', all: 'すべて', api_key: 'API キー', openai_base_url: 'OpenAI ベース URL', anthropic_base_url: 'Anthropic ベース URL', google_genai_base_url: 'Google GenAI ベース URL' },
    ko: { save: '저장', refresh: '새로 고침', import_zip: 'ZIP 가져오기', download_zip: 'ZIP 다운로드', download: '다운로드', clear: '지우기', reset_defaults: '기본값으로 재설정', check_for_updates: '업데이트 확인', time_range: '기간', one_day: '1일', seven_days: '7일', thirty_days: '30일', all: '전체', api_key: 'API 키', openai_base_url: 'OpenAI 기본 URL', anthropic_base_url: 'Anthropic 기본 URL', google_genai_base_url: 'Google GenAI 기본 URL' },
    pt: { save: 'Salvar', refresh: 'Atualizar', import_zip: 'Importar ZIP', download_zip: 'Baixar ZIP', download: 'Baixar', clear: 'Limpar', reset_defaults: 'Restaurar padrão', check_for_updates: 'Verificar atualizações', time_range: 'Período', one_day: '1 dia', seven_days: '7 dias', thirty_days: '30 dias', all: 'Todos', api_key: 'Chave de API', openai_base_url: 'URL base do OpenAI', anthropic_base_url: 'URL base do Anthropic', google_genai_base_url: 'URL base do Google GenAI' },
    ru: { save: 'Сохранить', refresh: 'Обновить', import_zip: 'Импортировать ZIP', download_zip: 'Скачать ZIP', download: 'Скачать', clear: 'Очистить', reset_defaults: 'Восстановить по умолчанию', check_for_updates: 'Проверить обновления', time_range: 'Период', one_day: '1 день', seven_days: '7 дней', thirty_days: '30 дней', all: 'Все', api_key: 'Ключ API', openai_base_url: 'Базовый URL OpenAI', anthropic_base_url: 'Базовый URL Anthropic', google_genai_base_url: 'Базовый URL Google GenAI' },
    th: { save: 'บันทึก', refresh: 'รีเฟรช', import_zip: 'นำเข้า ZIP', download_zip: 'ดาวน์โหลด ZIP', download: 'ดาวน์โหลด', clear: 'ล้าง', reset_defaults: 'คืนค่าเริ่มต้น', check_for_updates: 'ตรวจสอบการอัปเดต', time_range: 'ช่วงเวลา', one_day: '1 วัน', seven_days: '7 วัน', thirty_days: '30 วัน', all: 'ทั้งหมด', api_key: 'คีย์ API', openai_base_url: 'URL หลักของ OpenAI', anthropic_base_url: 'URL หลักของ Anthropic', google_genai_base_url: 'URL หลักของ Google GenAI' },
    tr: { save: 'Kaydet', refresh: 'Yenile', import_zip: 'ZIP içe aktar', download_zip: 'ZIP indir', download: 'İndir', clear: 'Temizle', reset_defaults: 'Varsayılanları geri yükle', check_for_updates: 'Güncellemeleri denetle', time_range: 'Zaman aralığı', one_day: '1 gün', seven_days: '7 gün', thirty_days: '30 gün', all: 'Tümü', api_key: 'API anahtarı', openai_base_url: 'OpenAI temel URL’si', anthropic_base_url: 'Anthropic temel URL’si', google_genai_base_url: 'Google GenAI temel URL’si' },
    vi: { save: 'Lưu', refresh: 'Làm mới', import_zip: 'Nhập ZIP', download_zip: 'Tải ZIP xuống', download: 'Tải xuống', clear: 'Xóa', reset_defaults: 'Khôi phục mặc định', check_for_updates: 'Kiểm tra bản cập nhật', time_range: 'Khoảng thời gian', one_day: '1 ngày', seven_days: '7 ngày', thirty_days: '30 ngày', all: 'Tất cả', api_key: 'Khóa API', openai_base_url: 'URL cơ sở OpenAI', anthropic_base_url: 'URL cơ sở Anthropic', google_genai_base_url: 'URL cơ sở Google GenAI' }
};

const OPERATIONAL_UI_TRANSLATIONS = {
    en: { total_credentials: 'Total credentials', active_credentials: 'Active credentials', disabled_credentials: 'Disabled credentials', select_all_visible: 'Select all visible', verify: 'Verify', provider: 'Provider', all_providers: 'All providers', status: 'Status', error: 'Error', cooldown: 'Cooldown', tier: 'Tier', per_page: 'Per page', previous: 'Previous', next: 'Next', none: 'None', enabled: 'Enabled', disabled: 'Disabled', in_cooldown: 'In cooldown', no_cooldown: 'No cooldown', free: 'Free', credential: 'Credential', requests: 'Requests', success: 'Success', tokens: 'Tokens', level: 'Level', warning: 'Warning', info: 'Info', debug: 'Debug', auto_scroll: 'Auto-scroll', available_provider_models: 'Available provider models', assigned_models: 'Models assigned to omway', unavailable_selections: 'Unavailable selections' },
    'zh-CN': { total_credentials: '凭据总数', active_credentials: '有效凭据', disabled_credentials: '已停用凭据', select_all_visible: '选择当前显示的全部项目', verify: '验证', provider: '提供商', all_providers: '所有提供商', status: '状态', error: '错误', cooldown: '冷却', tier: '方案等级', per_page: '每页数量', previous: '上一页', next: '下一页', none: '无', enabled: '已启用', disabled: '已停用', in_cooldown: '冷却中', no_cooldown: '未冷却', free: '免费', credential: '凭据', requests: '请求', success: '成功率', tokens: '令牌', level: '级别', warning: '警告', info: '信息', debug: '调试', auto_scroll: '自动滚动', available_provider_models: '可用的提供商模型', assigned_models: '已分配给 omway 的模型', unavailable_selections: '不可用的选择' },
    'zh-TW': { total_credentials: '憑證總數', active_credentials: '有效憑證', disabled_credentials: '已停用憑證', select_all_visible: '選取目前顯示的所有項目', verify: '驗證', provider: '供應商', all_providers: '所有供應商', status: '狀態', error: '錯誤', cooldown: '冷卻', tier: '方案等級', per_page: '每頁筆數', previous: '上一頁', next: '下一頁', none: '無', enabled: '已啟用', disabled: '已停用', in_cooldown: '冷卻中', no_cooldown: '未冷卻', free: '免費', credential: '憑證', requests: '請求', success: '成功率', tokens: '權杖', level: '層級', warning: '警告', info: '資訊', debug: '偵錯', auto_scroll: '自動捲動', available_provider_models: '可用的供應商模型', assigned_models: '已指派給 omway 的模型', unavailable_selections: '無法使用的選項' },
    de: { total_credentials: 'Zugänge insgesamt', active_credentials: 'Aktive Zugänge', disabled_credentials: 'Deaktivierte Zugänge', select_all_visible: 'Alle sichtbaren auswählen', verify: 'Prüfen', provider: 'Provider', all_providers: 'Alle Provider', status: 'Status', error: 'Fehler', cooldown: 'Abklingzeit', tier: 'Tarif', per_page: 'Pro Seite', previous: 'Zurück', next: 'Weiter', none: 'Keine', enabled: 'Aktiviert', disabled: 'Deaktiviert', in_cooldown: 'In Abklingzeit', no_cooldown: 'Keine Abklingzeit', free: 'Kostenlos', credential: 'Zugang', requests: 'Anfragen', success: 'Erfolg', tokens: 'Token', level: 'Stufe', warning: 'Warnung', info: 'Info', debug: 'Debug', auto_scroll: 'Automatisch scrollen', available_provider_models: 'Verfügbare Provider-Modelle', assigned_models: 'omway zugewiesene Modelle', unavailable_selections: 'Nicht verfügbare Auswahl' },
    es: { total_credentials: 'Credenciales totales', active_credentials: 'Credenciales activas', disabled_credentials: 'Credenciales desactivadas', select_all_visible: 'Seleccionar todo lo visible', verify: 'Verificar', provider: 'Proveedor', all_providers: 'Todos los proveedores', status: 'Estado', error: 'Error', cooldown: 'Espera', tier: 'Plan', per_page: 'Por página', previous: 'Anterior', next: 'Siguiente', none: 'Ninguno', enabled: 'Activa', disabled: 'Desactivada', in_cooldown: 'En espera', no_cooldown: 'Sin espera', free: 'Gratis', credential: 'Credencial', requests: 'Solicitudes', success: 'Éxito', tokens: 'Tokens', level: 'Nivel', warning: 'Advertencia', info: 'Información', debug: 'Depuración', auto_scroll: 'Desplazamiento automático', available_provider_models: 'Modelos de proveedores disponibles', assigned_models: 'Modelos asignados a omway', unavailable_selections: 'Selecciones no disponibles' },
    fr: { total_credentials: 'Identifiants au total', active_credentials: 'Identifiants actifs', disabled_credentials: 'Identifiants désactivés', select_all_visible: 'Tout sélectionner à l’écran', verify: 'Vérifier', provider: 'Fournisseur', all_providers: 'Tous les fournisseurs', status: 'État', error: 'Erreur', cooldown: 'Temporisation', tier: 'Offre', per_page: 'Par page', previous: 'Précédent', next: 'Suivant', none: 'Aucun', enabled: 'Activé', disabled: 'Désactivé', in_cooldown: 'En temporisation', no_cooldown: 'Aucune temporisation', free: 'Gratuit', credential: 'Identifiant', requests: 'Requêtes', success: 'Réussite', tokens: 'Jetons', level: 'Niveau', warning: 'Avertissement', info: 'Information', debug: 'Débogage', auto_scroll: 'Défilement automatique', available_provider_models: 'Modèles fournisseur disponibles', assigned_models: 'Modèles attribués à omway', unavailable_selections: 'Sélections indisponibles' },
    id: { total_credentials: 'Total kredensial', active_credentials: 'Kredensial aktif', disabled_credentials: 'Kredensial dinonaktifkan', select_all_visible: 'Pilih semua yang terlihat', verify: 'Verifikasi', provider: 'Penyedia', all_providers: 'Semua penyedia', status: 'Status', error: 'Kesalahan', cooldown: 'Masa tunggu', tier: 'Paket', per_page: 'Per halaman', previous: 'Sebelumnya', next: 'Berikutnya', none: 'Tidak ada', enabled: 'Aktif', disabled: 'Nonaktif', in_cooldown: 'Dalam masa tunggu', no_cooldown: 'Tanpa masa tunggu', free: 'Gratis', credential: 'Kredensial', requests: 'Permintaan', success: 'Keberhasilan', tokens: 'Token', level: 'Level', warning: 'Peringatan', info: 'Info', debug: 'Debug', auto_scroll: 'Gulir otomatis', available_provider_models: 'Model penyedia yang tersedia', assigned_models: 'Model yang ditetapkan ke omway', unavailable_selections: 'Pilihan tidak tersedia' },
    it: { total_credentials: 'Credenziali totali', active_credentials: 'Credenziali attive', disabled_credentials: 'Credenziali disabilitate', select_all_visible: 'Seleziona tutte le voci visibili', verify: 'Verifica', provider: 'Provider', all_providers: 'Tutti i provider', status: 'Stato', error: 'Errore', cooldown: 'Attesa', tier: 'Piano', per_page: 'Per pagina', previous: 'Precedente', next: 'Successivo', none: 'Nessuno', enabled: 'Abilitata', disabled: 'Disabilitata', in_cooldown: 'In attesa', no_cooldown: 'Nessuna attesa', free: 'Gratuito', credential: 'Credenziale', requests: 'Richieste', success: 'Successo', tokens: 'Token', level: 'Livello', warning: 'Avviso', info: 'Informazioni', debug: 'Debug', auto_scroll: 'Scorrimento automatico', available_provider_models: 'Modelli dei provider disponibili', assigned_models: 'Modelli assegnati a omway', unavailable_selections: 'Selezioni non disponibili' },
    ja: { total_credentials: '認証情報の総数', active_credentials: '有効な認証情報', disabled_credentials: '無効な認証情報', select_all_visible: '表示中の項目をすべて選択', verify: '検証', provider: 'プロバイダー', all_providers: 'すべてのプロバイダー', status: '状態', error: 'エラー', cooldown: 'クールダウン', tier: 'プラン', per_page: '1 ページの件数', previous: '前へ', next: '次へ', none: 'なし', enabled: '有効', disabled: '無効', in_cooldown: 'クールダウン中', no_cooldown: 'クールダウンなし', free: '無料', credential: '認証情報', requests: 'リクエスト', success: '成功率', tokens: 'トークン', level: 'レベル', warning: '警告', info: '情報', debug: 'デバッグ', auto_scroll: '自動スクロール', available_provider_models: '利用可能なプロバイダーモデル', assigned_models: 'omway に割り当てたモデル', unavailable_selections: '利用できない選択項目' },
    ko: { total_credentials: '전체 자격 증명', active_credentials: '활성 자격 증명', disabled_credentials: '비활성 자격 증명', select_all_visible: '표시된 항목 모두 선택', verify: '검증', provider: '공급자', all_providers: '모든 공급자', status: '상태', error: '오류', cooldown: '대기 시간', tier: '요금제', per_page: '페이지당', previous: '이전', next: '다음', none: '없음', enabled: '활성', disabled: '비활성', in_cooldown: '대기 중', no_cooldown: '대기 없음', free: '무료', credential: '자격 증명', requests: '요청', success: '성공률', tokens: '토큰', level: '수준', warning: '경고', info: '정보', debug: '디버그', auto_scroll: '자동 스크롤', available_provider_models: '사용 가능한 공급자 모델', assigned_models: 'omway에 할당된 모델', unavailable_selections: '사용할 수 없는 선택 항목' },
    pt: { total_credentials: 'Total de credenciais', active_credentials: 'Credenciais ativas', disabled_credentials: 'Credenciais desativadas', select_all_visible: 'Selecionar tudo que está visível', verify: 'Verificar', provider: 'Provedor', all_providers: 'Todos os provedores', status: 'Status', error: 'Erro', cooldown: 'Espera', tier: 'Plano', per_page: 'Por página', previous: 'Anterior', next: 'Próxima', none: 'Nenhum', enabled: 'Ativa', disabled: 'Desativada', in_cooldown: 'Em espera', no_cooldown: 'Sem espera', free: 'Grátis', credential: 'Credencial', requests: 'Solicitações', success: 'Sucesso', tokens: 'Tokens', level: 'Nível', warning: 'Aviso', info: 'Informação', debug: 'Depuração', auto_scroll: 'Rolagem automática', available_provider_models: 'Modelos de provedores disponíveis', assigned_models: 'Modelos atribuídos ao omway', unavailable_selections: 'Seleções indisponíveis' },
    ru: { total_credentials: 'Всего учётных данных', active_credentials: 'Активные учётные данные', disabled_credentials: 'Отключённые учётные данные', select_all_visible: 'Выбрать все видимые', verify: 'Проверить', provider: 'Провайдер', all_providers: 'Все провайдеры', status: 'Состояние', error: 'Ошибка', cooldown: 'Пауза', tier: 'Тариф', per_page: 'На странице', previous: 'Назад', next: 'Далее', none: 'Нет', enabled: 'Включено', disabled: 'Отключено', in_cooldown: 'На паузе', no_cooldown: 'Без паузы', free: 'Бесплатный', credential: 'Учётные данные', requests: 'Запросы', success: 'Успешность', tokens: 'Токены', level: 'Уровень', warning: 'Предупреждение', info: 'Информация', debug: 'Отладка', auto_scroll: 'Автопрокрутка', available_provider_models: 'Доступные модели провайдеров', assigned_models: 'Модели, назначенные omway', unavailable_selections: 'Недоступные варианты' },
    th: { total_credentials: 'ข้อมูลรับรองทั้งหมด', active_credentials: 'ข้อมูลรับรองที่ใช้งานอยู่', disabled_credentials: 'ข้อมูลรับรองที่ปิดใช้งาน', select_all_visible: 'เลือกทั้งหมดที่แสดง', verify: 'ตรวจสอบ', provider: 'ผู้ให้บริการ', all_providers: 'ผู้ให้บริการทั้งหมด', status: 'สถานะ', error: 'ข้อผิดพลาด', cooldown: 'ช่วงพัก', tier: 'แพ็กเกจ', per_page: 'ต่อหน้า', previous: 'ก่อนหน้า', next: 'ถัดไป', none: 'ไม่มี', enabled: 'เปิดใช้งาน', disabled: 'ปิดใช้งาน', in_cooldown: 'อยู่ในช่วงพัก', no_cooldown: 'ไม่มีช่วงพัก', free: 'ฟรี', credential: 'ข้อมูลรับรอง', requests: 'คำขอ', success: 'สำเร็จ', tokens: 'โทเค็น', level: 'ระดับ', warning: 'คำเตือน', info: 'ข้อมูล', debug: 'ดีบัก', auto_scroll: 'เลื่อนอัตโนมัติ', available_provider_models: 'โมเดลของผู้ให้บริการที่ใช้ได้', assigned_models: 'โมเดลที่กำหนดให้ omway', unavailable_selections: 'รายการที่ใช้ไม่ได้' },
    tr: { total_credentials: 'Toplam kimlik bilgisi', active_credentials: 'Etkin kimlik bilgileri', disabled_credentials: 'Devre dışı kimlik bilgileri', select_all_visible: 'Görünenlerin tümünü seç', verify: 'Doğrula', provider: 'Sağlayıcı', all_providers: 'Tüm sağlayıcılar', status: 'Durum', error: 'Hata', cooldown: 'Bekleme süresi', tier: 'Paket', per_page: 'Sayfa başına', previous: 'Önceki', next: 'Sonraki', none: 'Yok', enabled: 'Etkin', disabled: 'Devre dışı', in_cooldown: 'Beklemede', no_cooldown: 'Bekleme yok', free: 'Ücretsiz', credential: 'Kimlik bilgisi', requests: 'İstekler', success: 'Başarı', tokens: 'Belirteçler', level: 'Düzey', warning: 'Uyarı', info: 'Bilgi', debug: 'Hata ayıklama', auto_scroll: 'Otomatik kaydır', available_provider_models: 'Kullanılabilir sağlayıcı modelleri', assigned_models: 'omway’e atanan modeller', unavailable_selections: 'Kullanılamayan seçimler' },
    vi: { total_credentials: 'Tổng số thông tin xác thực', active_credentials: 'Thông tin xác thực đang hoạt động', disabled_credentials: 'Thông tin xác thực đã tắt', select_all_visible: 'Chọn tất cả mục đang hiển thị', verify: 'Xác minh', provider: 'Nhà cung cấp', all_providers: 'Tất cả nhà cung cấp', status: 'Trạng thái', error: 'Lỗi', cooldown: 'Thời gian tạm nghỉ', tier: 'Gói dịch vụ', per_page: 'Số mục mỗi trang', previous: 'Trang trước', next: 'Trang sau', none: 'Không có', enabled: 'Đang bật', disabled: 'Đã tắt', in_cooldown: 'Đang tạm nghỉ', no_cooldown: 'Không tạm nghỉ', free: 'Miễn phí', credential: 'Thông tin xác thực', requests: 'Yêu cầu', success: 'Tỷ lệ thành công', tokens: 'Token', level: 'Mức độ', warning: 'Cảnh báo', info: 'Thông tin', debug: 'Gỡ lỗi', auto_scroll: 'Tự động cuộn', available_provider_models: 'Mô hình nhà cung cấp khả dụng', assigned_models: 'Mô hình đã gán cho omway', unavailable_selections: 'Lựa chọn không khả dụng' }
};

const OPERATIONAL_ACTION_TRANSLATIONS = {
    en: { action_enable: 'Enable', action_disable: 'Disable', action_delete: 'Delete', action_enable_credit: 'Enable credits', action_disable_credit: 'Disable credits' },
    'zh-CN': { action_enable: '启用', action_disable: '停用', action_delete: '删除', action_enable_credit: '启用积分', action_disable_credit: '停用积分' },
    'zh-TW': { action_enable: '啟用', action_disable: '停用', action_delete: '刪除', action_enable_credit: '啟用點數', action_disable_credit: '停用點數' },
    de: { action_enable: 'Aktivieren', action_disable: 'Deaktivieren', action_delete: 'Löschen', action_enable_credit: 'Guthaben aktivieren', action_disable_credit: 'Guthaben deaktivieren' },
    es: { action_enable: 'Activar', action_disable: 'Desactivar', action_delete: 'Eliminar', action_enable_credit: 'Activar créditos', action_disable_credit: 'Desactivar créditos' },
    fr: { action_enable: 'Activer', action_disable: 'Désactiver', action_delete: 'Supprimer', action_enable_credit: 'Activer les crédits', action_disable_credit: 'Désactiver les crédits' },
    id: { action_enable: 'Aktifkan', action_disable: 'Nonaktifkan', action_delete: 'Hapus', action_enable_credit: 'Aktifkan kredit', action_disable_credit: 'Nonaktifkan kredit' },
    it: { action_enable: 'Abilita', action_disable: 'Disabilita', action_delete: 'Elimina', action_enable_credit: 'Abilita crediti', action_disable_credit: 'Disabilita crediti' },
    ja: { action_enable: '有効にする', action_disable: '無効にする', action_delete: '削除', action_enable_credit: 'クレジットを有効化', action_disable_credit: 'クレジットを無効化' },
    ko: { action_enable: '활성화', action_disable: '비활성화', action_delete: '삭제', action_enable_credit: '크레딧 사용', action_disable_credit: '크레딧 사용 안 함' },
    pt: { action_enable: 'Ativar', action_disable: 'Desativar', action_delete: 'Excluir', action_enable_credit: 'Ativar créditos', action_disable_credit: 'Desativar créditos' },
    ru: { action_enable: 'Включить', action_disable: 'Отключить', action_delete: 'Удалить', action_enable_credit: 'Включить кредиты', action_disable_credit: 'Отключить кредиты' },
    th: { action_enable: 'เปิดใช้งาน', action_disable: 'ปิดใช้งาน', action_delete: 'ลบ', action_enable_credit: 'เปิดใช้เครดิต', action_disable_credit: 'ปิดใช้เครดิต' },
    tr: { action_enable: 'Etkinleştir', action_disable: 'Devre dışı bırak', action_delete: 'Sil', action_enable_credit: 'Kredileri etkinleştir', action_disable_credit: 'Kredileri devre dışı bırak' },
    vi: { action_enable: 'Bật', action_disable: 'Tắt', action_delete: 'Xóa', action_enable_credit: 'Bật sử dụng credit', action_disable_credit: 'Tắt sử dụng credit' }
};

for (const [locale, messages] of Object.entries(OPERATIONAL_UI_TRANSLATIONS)) {
    Object.assign(COMMON_UI_TRANSLATIONS[locale], messages);
    Object.assign(COMMON_UI_TRANSLATIONS[locale], OPERATIONAL_ACTION_TRANSLATIONS[locale]);
}

const SETTINGS_LOCALE_TRANSLATIONS = {
    en: { language_region_title: 'Language and Region', language_region_description: 'Choose the language used by this browser for the console and its management messages.', display_language: 'Display language', language_browser_hint: 'Your choice is saved in this browser. New browsers start with the closest supported language for their region.' },
    'zh-CN': { language_region_title: '语言和地区', language_region_description: '选择此浏览器用于控制台及管理消息的语言。', display_language: '显示语言', language_browser_hint: '此选择仅保存在当前浏览器中。首次使用其他浏览器时，系统会根据所在地区选用最接近的受支持语言。' },
    'zh-TW': { language_region_title: '語言與地區', language_region_description: '選擇此瀏覽器在主控台及管理訊息中使用的語言。', display_language: '顯示語言', language_browser_hint: '此選項只會儲存在目前的瀏覽器。首次使用其他瀏覽器時，系統會依所在地區選用最接近的支援語言。' },
    de: { language_region_title: 'Sprache und Region', language_region_description: 'Wählen Sie die Sprache für die Konsole und ihre Verwaltungsmitteilungen in diesem Browser aus.', display_language: 'Anzeigesprache', language_browser_hint: 'Ihre Auswahl wird in diesem Browser gespeichert. In einem neuen Browser wird zunächst die am besten passende unterstützte Sprache für Ihre Region verwendet.' },
    es: { language_region_title: 'Idioma y región', language_region_description: 'Elige el idioma que utilizará este navegador en la consola y en sus mensajes de administración.', display_language: 'Idioma de la interfaz', language_browser_hint: 'La selección se guarda en este navegador. En un navegador nuevo se utilizará inicialmente el idioma compatible más apropiado para tu región.' },
    fr: { language_region_title: 'Langue et région', language_region_description: 'Choisissez la langue utilisée par ce navigateur pour la console et ses messages d’administration.', display_language: 'Langue d’affichage', language_browser_hint: 'Votre choix est enregistré dans ce navigateur. Sur un nouveau navigateur, la langue prise en charge la plus adaptée à votre région est sélectionnée au départ.' },
    id: { language_region_title: 'Bahasa dan Wilayah', language_region_description: 'Pilih bahasa yang digunakan browser ini untuk konsol dan pesan pengelolaannya.', display_language: 'Bahasa tampilan', language_browser_hint: 'Pilihan disimpan di browser ini. Browser baru akan menggunakan bahasa yang didukung dan paling sesuai dengan wilayah Anda.' },
    it: { language_region_title: 'Lingua e area geografica', language_region_description: 'Scegli la lingua usata da questo browser per la console e i relativi messaggi di gestione.', display_language: 'Lingua di visualizzazione', language_browser_hint: 'La scelta viene salvata in questo browser. Un nuovo browser utilizzerà inizialmente la lingua supportata più adatta alla tua area geografica.' },
    ja: { language_region_title: '言語と地域', language_region_description: 'このブラウザーでコンソールと管理メッセージに使用する言語を選択します。', display_language: '表示言語', language_browser_hint: '選択内容はこのブラウザーに保存されます。別のブラウザーでは、初回に地域に最も適した対応言語が選択されます。' },
    ko: { language_region_title: '언어 및 지역', language_region_description: '이 브라우저에서 콘솔과 관리 메시지에 사용할 언어를 선택하세요.', display_language: '표시 언어', language_browser_hint: '선택한 언어는 이 브라우저에 저장됩니다. 새 브라우저에서는 지역에 가장 적합한 지원 언어가 우선 적용됩니다.' },
    pt: { language_region_title: 'Idioma e região', language_region_description: 'Escolha o idioma usado por este navegador no console e nas mensagens de gerenciamento.', display_language: 'Idioma de exibição', language_browser_hint: 'A escolha fica salva neste navegador. Em um navegador novo, será usado inicialmente o idioma compatível mais adequado à sua região.' },
    ru: { language_region_title: 'Язык и регион', language_region_description: 'Выберите язык интерфейса консоли и служебных сообщений в этом браузере.', display_language: 'Язык интерфейса', language_browser_hint: 'Выбор сохраняется в этом браузере. В новом браузере сначала будет выбран наиболее подходящий для вашего региона поддерживаемый язык.' },
    th: { language_region_title: 'ภาษาและภูมิภาค', language_region_description: 'เลือกภาษาที่เบราว์เซอร์นี้ใช้ในคอนโซลและข้อความการจัดการ', display_language: 'ภาษาที่แสดง', language_browser_hint: 'ตัวเลือกนี้จะบันทึกไว้ในเบราว์เซอร์ปัจจุบัน เมื่อใช้เบราว์เซอร์ใหม่ ระบบจะเลือกภาษาที่รองรับและเหมาะกับภูมิภาคของคุณมากที่สุดก่อน' },
    tr: { language_region_title: 'Dil ve Bölge', language_region_description: 'Bu tarayıcıda konsol ve yönetim iletileri için kullanılacak dili seçin.', display_language: 'Görüntüleme dili', language_browser_hint: 'Seçiminiz bu tarayıcıya kaydedilir. Yeni bir tarayıcıda önce bölgenize en uygun desteklenen dil kullanılır.' },
    vi: { language_region_title: 'Ngôn ngữ và khu vực', language_region_description: 'Chọn ngôn ngữ mà trình duyệt này sử dụng cho bảng điều khiển và các thông báo quản trị.', display_language: 'Ngôn ngữ hiển thị', language_browser_hint: 'Lựa chọn được lưu trong trình duyệt này. Trình duyệt mới sẽ bắt đầu bằng ngôn ngữ được hỗ trợ phù hợp nhất với khu vực của bạn.' }
};

const AUTH_LOCALE_TRANSLATIONS = {
    en: { password_min_placeholder: 'At least 8 characters', password_confirm_placeholder: 'Re-enter password', setup_token: 'Setup token', setup_token_placeholder: 'Enter the token from the application logs', setup_token_hint: 'Remote setup requires the one-time token printed in the container or application logs.', password_min_error: 'Password must be at least 8 characters.', password_match_error: 'Passwords do not match.', setup_completed: 'Initial setup completed.', setup_failed: 'Initial setup failed.' },
    'zh-CN': { password_min_placeholder: '至少 8 个字符', password_confirm_placeholder: '再次输入密码', setup_token: '设置令牌', setup_token_placeholder: '输入应用日志中的令牌', setup_token_hint: '远程设置需要容器或应用日志中输出的一次性令牌。', password_min_error: '密码必须至少包含 8 个字符。', password_match_error: '两次输入的密码不一致。', setup_completed: '初始设置已完成。', setup_failed: '初始设置失败。' },
    'zh-TW': { password_min_placeholder: '至少 8 個字元', password_confirm_placeholder: '再次輸入密碼', setup_token: '設定權杖', setup_token_placeholder: '輸入應用程式記錄中的權杖', setup_token_hint: '遠端設定需要容器或應用程式記錄中顯示的一次性權杖。', password_min_error: '密碼至少須包含 8 個字元。', password_match_error: '兩次輸入的密碼不一致。', setup_completed: '初始設定已完成。', setup_failed: '初始設定失敗。' },
    de: { password_min_placeholder: 'Mindestens 8 Zeichen', password_confirm_placeholder: 'Passwort erneut eingeben', setup_token: 'Einrichtungstoken', setup_token_placeholder: 'Token aus dem Anwendungsprotokoll eingeben', setup_token_hint: 'Für die Einrichtung aus der Ferne ist das einmalige Token aus dem Container- oder Anwendungsprotokoll erforderlich.', password_min_error: 'Das Passwort muss mindestens 8 Zeichen lang sein.', password_match_error: 'Die Passwörter stimmen nicht überein.', setup_completed: 'Die Ersteinrichtung ist abgeschlossen.', setup_failed: 'Die Ersteinrichtung ist fehlgeschlagen.' },
    es: { password_min_placeholder: '8 caracteres como mínimo', password_confirm_placeholder: 'Vuelve a escribir la contraseña', setup_token: 'Token de configuración', setup_token_placeholder: 'Introduce el token de los registros de la aplicación', setup_token_hint: 'La configuración remota requiere el token de un solo uso que aparece en los registros del contenedor o de la aplicación.', password_min_error: 'La contraseña debe tener al menos 8 caracteres.', password_match_error: 'Las contraseñas no coinciden.', setup_completed: 'La configuración inicial se completó correctamente.', setup_failed: 'No se pudo completar la configuración inicial.' },
    fr: { password_min_placeholder: '8 caractères minimum', password_confirm_placeholder: 'Saisissez à nouveau le mot de passe', setup_token: 'Jeton de configuration', setup_token_placeholder: 'Saisissez le jeton indiqué dans les journaux de l’application', setup_token_hint: 'La configuration à distance nécessite le jeton à usage unique affiché dans les journaux du conteneur ou de l’application.', password_min_error: 'Le mot de passe doit comporter au moins 8 caractères.', password_match_error: 'Les mots de passe ne correspondent pas.', setup_completed: 'La configuration initiale est terminée.', setup_failed: 'La configuration initiale a échoué.' },
    id: { password_min_placeholder: 'Minimal 8 karakter', password_confirm_placeholder: 'Masukkan kembali kata sandi', setup_token: 'Token penyiapan', setup_token_placeholder: 'Masukkan token dari log aplikasi', setup_token_hint: 'Penyiapan jarak jauh memerlukan token sekali pakai yang tercetak di log container atau aplikasi.', password_min_error: 'Kata sandi harus berisi minimal 8 karakter.', password_match_error: 'Kata sandi tidak sama.', setup_completed: 'Penyiapan awal selesai.', setup_failed: 'Penyiapan awal gagal.' },
    it: { password_min_placeholder: 'Almeno 8 caratteri', password_confirm_placeholder: 'Inserisci di nuovo la password', setup_token: 'Token di configurazione', setup_token_placeholder: 'Inserisci il token mostrato nei log dell’applicazione', setup_token_hint: 'La configurazione remota richiede il token monouso riportato nei log del container o dell’applicazione.', password_min_error: 'La password deve contenere almeno 8 caratteri.', password_match_error: 'Le password non corrispondono.', setup_completed: 'Configurazione iniziale completata.', setup_failed: 'Configurazione iniziale non riuscita.' },
    ja: { password_min_placeholder: '8 文字以上', password_confirm_placeholder: 'パスワードを再入力', setup_token: 'セットアップトークン', setup_token_placeholder: 'アプリケーションログに表示されたトークンを入力', setup_token_hint: 'リモートセットアップには、コンテナーまたはアプリケーションログに表示されるワンタイムトークンが必要です。', password_min_error: 'パスワードは 8 文字以上にしてください。', password_match_error: 'パスワードが一致しません。', setup_completed: '初期セットアップが完了しました。', setup_failed: '初期セットアップに失敗しました。' },
    ko: { password_min_placeholder: '8자 이상', password_confirm_placeholder: '비밀번호 다시 입력', setup_token: '설정 토큰', setup_token_placeholder: '애플리케이션 로그의 토큰 입력', setup_token_hint: '원격 설정에는 컨테이너 또는 애플리케이션 로그에 표시된 일회용 토큰이 필요합니다.', password_min_error: '비밀번호는 8자 이상이어야 합니다.', password_match_error: '비밀번호가 일치하지 않습니다.', setup_completed: '초기 설정을 완료했습니다.', setup_failed: '초기 설정에 실패했습니다.' },
    pt: { password_min_placeholder: 'Pelo menos 8 caracteres', password_confirm_placeholder: 'Digite a senha novamente', setup_token: 'Token de configuração', setup_token_placeholder: 'Digite o token exibido nos logs do aplicativo', setup_token_hint: 'A configuração remota exige o token de uso único exibido nos logs do contêiner ou do aplicativo.', password_min_error: 'A senha deve ter pelo menos 8 caracteres.', password_match_error: 'As senhas não coincidem.', setup_completed: 'Configuração inicial concluída.', setup_failed: 'Falha na configuração inicial.' },
    ru: { password_min_placeholder: 'Не менее 8 символов', password_confirm_placeholder: 'Введите пароль ещё раз', setup_token: 'Токен настройки', setup_token_placeholder: 'Введите токен из журнала приложения', setup_token_hint: 'Для удалённой настройки требуется одноразовый токен, указанный в журнале контейнера или приложения.', password_min_error: 'Пароль должен содержать не менее 8 символов.', password_match_error: 'Пароли не совпадают.', setup_completed: 'Первоначальная настройка завершена.', setup_failed: 'Не удалось завершить первоначальную настройку.' },
    th: { password_min_placeholder: 'อย่างน้อย 8 ตัวอักษร', password_confirm_placeholder: 'ป้อนรหัสผ่านอีกครั้ง', setup_token: 'โทเค็นสำหรับตั้งค่า', setup_token_placeholder: 'ป้อนโทเค็นจากบันทึกของแอปพลิเคชัน', setup_token_hint: 'การตั้งค่าจากระยะไกลต้องใช้โทเค็นแบบใช้ครั้งเดียวที่แสดงในบันทึกของคอนเทนเนอร์หรือแอปพลิเคชัน', password_min_error: 'รหัสผ่านต้องมีอย่างน้อย 8 ตัวอักษร', password_match_error: 'รหัสผ่านไม่ตรงกัน', setup_completed: 'ตั้งค่าเริ่มต้นเรียบร้อยแล้ว', setup_failed: 'ตั้งค่าเริ่มต้นไม่สำเร็จ' },
    tr: { password_min_placeholder: 'En az 8 karakter', password_confirm_placeholder: 'Parolayı yeniden girin', setup_token: 'Kurulum belirteci', setup_token_placeholder: 'Uygulama günlüklerindeki belirteci girin', setup_token_hint: 'Uzaktan kurulum için kapsayıcı veya uygulama günlüklerinde gösterilen tek kullanımlık belirteç gerekir.', password_min_error: 'Parola en az 8 karakter olmalıdır.', password_match_error: 'Parolalar eşleşmiyor.', setup_completed: 'İlk kurulum tamamlandı.', setup_failed: 'İlk kurulum başarısız oldu.' },
    vi: { password_min_placeholder: 'Tối thiểu 8 ký tự', password_confirm_placeholder: 'Nhập lại mật khẩu', setup_token: 'Mã thiết lập', setup_token_placeholder: 'Nhập mã trong nhật ký ứng dụng', setup_token_hint: 'Thiết lập từ xa cần mã dùng một lần được in trong nhật ký của container hoặc ứng dụng.', password_min_error: 'Mật khẩu phải có ít nhất 8 ký tự.', password_match_error: 'Mật khẩu xác nhận không khớp.', setup_completed: 'Đã hoàn tất thiết lập ban đầu.', setup_failed: 'Không thể hoàn tất thiết lập ban đầu.' }
};

const DIALOG_LOCALE_TRANSLATIONS = {
    en: { available_models_title: 'Available Models', no_models_for_credential: 'No model information is available for this credential.', model_test_title: 'Model Test', credential_details_title: 'Credential Details', credential_verification_title: 'Credential Verification', preview_configuration_title: 'Preview Channel Configuration', pool_import_title: 'Pool Import', batch_verification_title: 'Batch Verification', provider_batch_verification_title: 'Provider Batch Verification' },
    'zh-CN': { available_models_title: '可用模型', no_models_for_credential: '此凭据暂无可用的模型信息。', model_test_title: '模型测试', credential_details_title: '凭据详情', credential_verification_title: '凭据验证', preview_configuration_title: '预览通道配置', pool_import_title: '凭据池导入', batch_verification_title: '批量验证', provider_batch_verification_title: '提供商凭据批量验证' },
    'zh-TW': { available_models_title: '可用模型', no_models_for_credential: '此憑證目前沒有可用的模型資訊。', model_test_title: '模型測試', credential_details_title: '憑證詳細資料', credential_verification_title: '憑證驗證', preview_configuration_title: '預覽通道設定', pool_import_title: '憑證集區匯入', batch_verification_title: '批次驗證', provider_batch_verification_title: '供應商憑證批次驗證' },
    de: { available_models_title: 'Verfügbare Modelle', no_models_for_credential: 'Für diesen Zugang sind keine Modellinformationen verfügbar.', model_test_title: 'Modelltest', credential_details_title: 'Zugangsdaten', credential_verification_title: 'Zugangsdaten prüfen', preview_configuration_title: 'Vorschaukanal konfigurieren', pool_import_title: 'Zugangspool importieren', batch_verification_title: 'Stapelprüfung', provider_batch_verification_title: 'Provider-Zugänge stapelweise prüfen' },
    es: { available_models_title: 'Modelos disponibles', no_models_for_credential: 'No hay información de modelos disponible para esta credencial.', model_test_title: 'Prueba de modelo', credential_details_title: 'Detalles de la credencial', credential_verification_title: 'Verificación de credencial', preview_configuration_title: 'Configuración del canal de vista previa', pool_import_title: 'Importación del pool', batch_verification_title: 'Verificación por lotes', provider_batch_verification_title: 'Verificación por lotes del proveedor' },
    fr: { available_models_title: 'Modèles disponibles', no_models_for_credential: 'Aucune information de modèle n’est disponible pour cet identifiant.', model_test_title: 'Test du modèle', credential_details_title: 'Détails de l’identifiant', credential_verification_title: 'Vérification de l’identifiant', preview_configuration_title: 'Configuration du canal Preview', pool_import_title: 'Importation du pool', batch_verification_title: 'Vérification groupée', provider_batch_verification_title: 'Vérification groupée du fournisseur' },
    id: { available_models_title: 'Model yang Tersedia', no_models_for_credential: 'Informasi model tidak tersedia untuk kredensial ini.', model_test_title: 'Uji Model', credential_details_title: 'Detail Kredensial', credential_verification_title: 'Verifikasi Kredensial', preview_configuration_title: 'Konfigurasi Kanal Pratinjau', pool_import_title: 'Impor Pool', batch_verification_title: 'Verifikasi Massal', provider_batch_verification_title: 'Verifikasi Massal Penyedia' },
    it: { available_models_title: 'Modelli disponibili', no_models_for_credential: 'Non sono disponibili informazioni sui modelli per questa credenziale.', model_test_title: 'Test del modello', credential_details_title: 'Dettagli della credenziale', credential_verification_title: 'Verifica della credenziale', preview_configuration_title: 'Configurazione del canale Preview', pool_import_title: 'Importazione del pool', batch_verification_title: 'Verifica in blocco', provider_batch_verification_title: 'Verifica in blocco del provider' },
    ja: { available_models_title: '利用可能なモデル', no_models_for_credential: 'この認証情報で利用できるモデル情報はありません。', model_test_title: 'モデルテスト', credential_details_title: '認証情報の詳細', credential_verification_title: '認証情報の検証', preview_configuration_title: 'プレビューチャネルの設定', pool_import_title: 'プールのインポート', batch_verification_title: '一括検証', provider_batch_verification_title: 'プロバイダー認証情報の一括検証' },
    ko: { available_models_title: '사용 가능한 모델', no_models_for_credential: '이 자격 증명에 사용할 수 있는 모델 정보가 없습니다.', model_test_title: '모델 테스트', credential_details_title: '자격 증명 세부 정보', credential_verification_title: '자격 증명 검증', preview_configuration_title: 'Preview 채널 설정', pool_import_title: '풀 가져오기', batch_verification_title: '일괄 검증', provider_batch_verification_title: '공급자 자격 증명 일괄 검증' },
    pt: { available_models_title: 'Modelos disponíveis', no_models_for_credential: 'Não há informações de modelos disponíveis para esta credencial.', model_test_title: 'Teste de modelo', credential_details_title: 'Detalhes da credencial', credential_verification_title: 'Verificação da credencial', preview_configuration_title: 'Configuração do canal de visualização', pool_import_title: 'Importação do pool', batch_verification_title: 'Verificação em lote', provider_batch_verification_title: 'Verificação em lote do provedor' },
    ru: { available_models_title: 'Доступные модели', no_models_for_credential: 'Для этих учётных данных нет сведений о доступных моделях.', model_test_title: 'Проверка модели', credential_details_title: 'Сведения об учётных данных', credential_verification_title: 'Проверка учётных данных', preview_configuration_title: 'Настройка канала Preview', pool_import_title: 'Импорт пула', batch_verification_title: 'Пакетная проверка', provider_batch_verification_title: 'Пакетная проверка учётных данных провайдера' },
    th: { available_models_title: 'โมเดลที่ใช้ได้', no_models_for_credential: 'ไม่มีข้อมูลโมเดลสำหรับข้อมูลรับรองนี้', model_test_title: 'ทดสอบโมเดล', credential_details_title: 'รายละเอียดข้อมูลรับรอง', credential_verification_title: 'ตรวจสอบข้อมูลรับรอง', preview_configuration_title: 'ตั้งค่าช่องทาง Preview', pool_import_title: 'นำเข้าพูล', batch_verification_title: 'ตรวจสอบแบบกลุ่ม', provider_batch_verification_title: 'ตรวจสอบข้อมูลรับรองของผู้ให้บริการแบบกลุ่ม' },
    tr: { available_models_title: 'Kullanılabilir Modeller', no_models_for_credential: 'Bu kimlik bilgisi için model bilgisi bulunmuyor.', model_test_title: 'Model Testi', credential_details_title: 'Kimlik Bilgisi Ayrıntıları', credential_verification_title: 'Kimlik Bilgisi Doğrulama', preview_configuration_title: 'Preview Kanalı Yapılandırması', pool_import_title: 'Havuz İçe Aktarma', batch_verification_title: 'Toplu Doğrulama', provider_batch_verification_title: 'Sağlayıcı Kimlik Bilgilerini Toplu Doğrulama' },
    vi: { available_models_title: 'Mô hình khả dụng', no_models_for_credential: 'Thông tin xác thực này chưa có dữ liệu về mô hình khả dụng.', model_test_title: 'Kiểm tra mô hình', credential_details_title: 'Chi tiết thông tin xác thực', credential_verification_title: 'Xác minh thông tin xác thực', preview_configuration_title: 'Cấu hình kênh Preview', pool_import_title: 'Nhập kho thông tin xác thực', batch_verification_title: 'Xác minh hàng loạt', provider_batch_verification_title: 'Xác minh hàng loạt theo nhà cung cấp' }
};
