services:
  - type: web
    name: router
    runtime: docker
    dockerfilePath: ./deploy/Dockerfile
    dockerContext: .
    plan: free
    region: singapore
    healthCheckPath: /
    envVars:
      - key: PASSWORD
        sync: false
      - key: HOST
        value: 0.0.0.0
      - key: PORT
        value: "10000"
